version: '3.7'

services:

  sample-prod:
    container_name: sample-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '1337:80'
    environment:
      - BACKEND_URL="http://3.90.123.49:8000" 
