version: "3.8"
services: 
  redis-broker:
    image: redis
    container_name: redis-broker
    restart: always
    ports:
      - '6379:6379'
  celeris-worker:
    build: 
      context: .
      dockerfile: dockerfile_celery
    depends_on:
      - redis-broker
      - libros-api
  libros-api:
    build: .
    container_name: libros_api_app
    networks:
      - web_net
    ports:
     - "8000:8000"
    depends_on: 
      db:
        condition: service_healthy
  db: 
    container_name: libro_db_pg
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: libros
      POSTGRES_DB: libros
    image: "postgres:latest"
    networks:
      - web_net
    ports: 
      - "5432:5432"
    volumes: 
      - ${PWD}/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
    web_net:
        driver: bridge

volumes: 
  pg-data: 
    driver: local