# Use an official Python runtime as the base image
FROM ubuntu

# Set the working directory in the container to /app
RUN apt-get update -y
RUN apt-get install python3-pip -y

# Copy the rest of the application code to the container
COPY . .

# Install the dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose port 8000 for the Flask development server to listen on
EXPOSE 8000

# Define the command to run the Flask development server
ENTRYPOINT celery -A tasks worker --autoscale 10 --loglevel=info