version: "3.8"
services: 
  redis-broker:
    image: redis
    container_name: redis-broker
    restart: always
    ports:
      - '6379:6379'
  celeris-worker:
    container_name: celery-worker
    build: .
    volumes:
      - /nfs/home/original_files:/compressed
      - /nfs/home/processed_files:/processed_files

    depends_on:
      - redis-broker
