version: "3.8"
services: 
  files-api:
    build: .
    container_name: files_api
    networks:
      - web_net
    ports:
     - "8000:8000"
    volumes:
      - /nfs/home/original_files:/back/original_files
      - /nfs/home/processed_files:/back/processed_files
    depends_on: 
      db:
        condition: service_healthy
  db: 
    container_name: libro_db_pg
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: libros
      POSTGRES_DB: libros
    image: "postgres:latest"
    networks:
      - web_net
    ports: 
      - "5432:5432"
    volumes: 
      - ${PWD}/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
    web_net:
        driver: bridge

volumes: 
  pg-data: 
    driver: local